version: '3.5'

services:
  postgres:
    container_name: postgres_test_container
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres-test
    volumes:
      - postgres:/data/postgres
    ports:
      - '5433:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
